services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - finance-net

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4200:80"  # Angular via Nginx
    depends_on:
      - backend
    networks:
      - finance-net

networks:
  finance-net:

